export const FETCH_MEMBERS = "FETCH_MEMBERS";
export const GET_ALL_MEMBERS = "GET_ALL_MEMBERS";
export const GET_ALL_MEMBER_DATA = "GET_ALL_MEMBER_DATA";
export const LOGIN = "LOGIN";
export const LOGIN_ERR = "LOGIN_ERR";
export const REGISTER = "REGISTER";
export const REGISTER_ERR = "REGISTER_ERR";
export const REGISTER_RESET = "REGISTER_RESET";
export const SET_LOGGED_INFO = "SET_LOGGED_INFO";
export const GET_LOGGED_INFO = "GET_LOGGED_INFO";
export const CHECK_PASSWORD = 'CHECK_PASSWORD';
export const CHECK_PASSWORD_RESET = 'CHECK_PASSWORD_RESET';
export const EDIT_EMAIL = 'EDIT_EMAIL'
export const EDIT_EMAIL_RESET = 'EDIT_EMAIL_RESET'
// edit my profile
export const EDIT_MYPROFILE = "EDIT_MYPROFILE";
// edit my info
export const EDIT_MYINFO = "EDIT_MYINFO";
export const EDIT_MYINFO_ERR = "EDIT_MYINFO_ERR";
export const EDIT_MYINFO_CHANGE_RESET = "EDIT_MYINFO_CHANGE_RESET";
// edit my color
export const EDIT_MY_COLOR_FAIL = "EDIT_MY_COLOR_FAIL";
export const EDIT_MY_COLOR_FAIL_RESET = "EDIT_MY_COLOR_FAIL_RESET";
// edit password
export const EDIT_PASSWORD_SUCCESS = "EDIT_PASSWORD_SUCCESS";
export const EDIT_PASSWORD_SUCCESS_RESET = "EDIT_PASSWORD_SUCCESS_RESET";
export const EDIT_PASSWORD_FAIL = "EDIT_PASSWORD_FAIL";
export const EDIT_PASSWORD_FAIL_RESET = "EDIT_PASSWORD_FAIL_RESET";

export const LOGOUT = "LOGOUT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_ERR = "DELETE_ACCOUNT_ERR";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const GET_OTHER_MEMBER = "GET_OTHER_MEMBER";

export const FIND_ID_SUCCESS = "FIND_ID_SUCCESS";
export const FIND_ID_SUCCESS_RESET = "FIND_ID_SUCCESS_RESET";
export const FIND_ID_FAIL = "FIND_ID_FAIL";
export const FIND_ID_FAIL_RESET = "FIND_ID_FAIL_RESET";

export const EXIST_EMAIL_FAIL = "EXIST_EMAIL_FAIL"
export const EXIST_EMAIL_FAIL_RESET = "EXIST_EMAIL_FAIL_RESET"
export const EXIST_EMAIL_SUCCESS = "EXIST_EMAIL_SUCCESS"
export const EXIST_EMAIL_SUCCESS_RESET = "EXIST_EMAIL_SUCCESS_RESET"

export const FIND_PW_SUCCESS = "FIND_PW_SUCCESS";
export const FIND_PW_SUCCESS_RESET = "FIND_PW_SUCCESS_RESET";
export const FIND_PW_FAIL = "FIND_PW_FAIL";
export const FIND_PW_FAIL_RESET = "FIND_PW_FAIL_RESET";

export const MATCH_ID_EMAIL_SUCCESS = "MATCH_ID_EMAIL_SUCCESS"
export const MATCH_ID_EMAIL_SUCCESS_RESET = "MATCH_ID_EMAIL_SUCCESS_RESET"
export const MATCH_ID_EMAIL_FAIL = "MATCH_ID_EMAIL_FAIL"
export const MATCH_ID_EMAIL_FAIL_RESET = "MATCH_ID_EMAIL_FAIL_RESET"

export const DRAG_HAPPENED = "DRAG_HAPPENED";
export const ADD_BOARD = "ADD_BOARD";
export const FETCH_DAILY_LIST = "FETCH_DAILY_LIST";
export const FETCH_TODO_LIST = "FETCH_TODO_LIST";
export const FETCH_LIST = "FETCH_LIST";
export const ADD_LIST = "ADD_LIST";
export const EDIT_LIST = "EDIT_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const FETCH_CARDS = "FETCH_CARDS";
export const ADD_CARD = "ADD_CARD";
export const EDIT_CARD = "EDIT_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const FETCH_STATISTICS_MEMBER = "FETCH_STATISTICS_MEMBER";
export const FETCH_STATISTICS_DATA = "FETCH_STATISTICS_DATA";

// search action
export const SEARCH_KEYWORD = "SEARCH_KEYWORD";
export const SEARCH_CARDLIST = "SEARCH_CARDLIST";
// tag action
export const MEM_TAG = "MEM_TAG";
export const GET_ALL_TAG = "GET_ALL_TAG";
export const FETCH_TAG = "FETCH_TAG";

//heatmap action

export const GET_DAILY_TASK = "GET_DAILY_TASK";
export const GET_DAILY_TASK_RESET = "GET_DAILY_TASK_RESET"
export const GET_DAILY_CAL = "GET_DAILY_CAL";
export const GET_DAILY_LIST = "GET_DAILY_LIST";

export const SET_EDIT_MODE_LIST = "SET_EDIT_MODE_LIST";
export const SET_EDIT_MODE_CARD = "SET_EDIT_MODE_CARD";

//cardlist - tag action
export const DELETE_TAG = "DELETE_TAG";
export const ADD_TAG = "ADD_TAG";

//comment
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const PUT_COMMENT = "PUT_COMMENT";

export const FETCH_ALARMS = "FETCH_ALARMS";
export const READ_ALARM = "READ_ALARM";
export const READ_ALL_ALARM = "READ_ALL_ALARM";
export const ADD_ALARM = "ADD_ALARM";
